- src: git+ssh://gitlab@git.forgeservicelab.fi:10022/ansible-roles/birt-viewer.git
  path: roles/
  name: birt-viewer

- src: git+ssh://gitlab@git.forgeservicelab.fi:10022/ansible-roles/birt-reports.git
  path: roles/
  name: birt-reports
